livery = {
    {"Aircraft_01", DIFFUSE , "Aircraft 01_BaseColor", false};
    {"Aircraft_01.002", DIFFUSE , "Aircraft 01_BaseColor", false};
    {"Aircraft_02", DIFFUSE , "Aircraft 02_BaseColor", false};
    {"Aircraft_02.002", DIFFUSE , "Aircraft 02_BaseColor", false};
    {"Aircraft_03", DIFFUSE , "Aircraft 03_BaseColor", false};
    {"BANO-YELLOW", DIFFUSE , "f15_bano", false};
    {"BANO-YELLOW.001", DIFFUSE , "f15_bano", false};
    {"BANO-YELLOW.002", DIFFUSE , "f15_bano", false};
    {"BANO-YELLOW.003", DIFFUSE , "f15_bano", false};
    {"BANO-YELLOW.004", DIFFUSE , "f15_bano", false};
    {"Bay_Front", DIFFUSE , "Bay Front_BaseColor", false};
    {"Bay_Left", DIFFUSE , "Bay Left_BaseColor", false};
    {"Bay_missiles", DIFFUSE , "Bay missiles_BaseColor", false};
    {"Bay_Right", DIFFUSE , "Bay Right_BaseColor", false};
    {"Black", DIFFUSE , "black", false};
    {"Black.001", DIFFUSE , "White", false};
    {"Black.005", DIFFUSE , "white", false};
    {"Black.008", DIFFUSE , "white", false};
    {"Cockpit_01", DIFFUSE , "Cockpit 01_BaseColor", false};
    {"Cockpit_02", DIFFUSE , "Cockpit 02_BaseColor", false};
    {"Cockpit_02.001", DIFFUSE , "Cockpit 02_BaseColor", false};
    {"Cockpit_03", DIFFUSE , "Cockpit 03_BaseColor", false};
    {"Cockpit_03.001", DIFFUSE , "Cockpit 03_BaseColor", false};
    {"Cockpit_04", DIFFUSE , "Cockpit 04_BaseColor", false};
    {"Door_Missiles_Left", DIFFUSE , "Door Missiles Left_BaseColor", false};
    {"Door_Missiles_Right", DIFFUSE , "Door Missiles Right_BaseColor", false};
    {"Fuselage", DIFFUSE , "white", false};
    {"Gear_front", DIFFUSE , "Gear front_BaseColor", false};
    {"Gear_front.001", DIFFUSE , "Gear front_BaseColor", false};
    {"Gear_Left", DIFFUSE , "Gear Left_BaseColor", false};
    {"Gear_Left.001", DIFFUSE , "Gear Left_BaseColor", false};
    {"Gear_Right", DIFFUSE , "Gear Right_BaseColor", false};
    {"Gear_Right.001", DIFFUSE , "Gear Right_BaseColor", false};
    {"HGU-55.002", DIFFUSE , "hgu55", false};
    {"HGU-55.002", NORMAL_MAP , "hgu55_nm", false};
    {"Hud", DIFFUSE , "green", false};
    {"Left_bay_1", DIFFUSE , "Bay Left_BaseColor", false};
    {"Left_bay_2", DIFFUSE , "Bay Left_BaseColor", false};
    {"Left_bomb_door", DIFFUSE , "Door Missiles Left_BaseColor", false};
    {"m0mat", DIFFUSE , "black", false};
    {"m21mat", DIFFUSE , "texture", false};
    {"m23mat", DIFFUSE , "black", false};
    {"m43mat", DIFFUSE , "black", false};
    {"Material", DIFFUSE , "hgu55", false};
    {"Material.002", DIFFUSE , "Aircraft 03_BaseColor", false};
    {"Material.004", DIFFUSE , "Aircraft 03_BaseColor", false};
    {"Material.005", DIFFUSE , "Aircraft 03_BaseColor", false};
    {"Material.007", DIFFUSE , "F-117_Turbine", false};
    {"Material.008", DIFFUSE , "F-117_glass", false};
    {"Material.010", DIFFUSE , "Aircraft 03_BaseColor", false};
    {"Material.011", DIFFUSE , "black", false};
    {"Material.012", DIFFUSE , "black", false};
    {"Material.013", DIFFUSE , "Aircraft 03_BaseColor", false};
    {"Material.014", DIFFUSE , "F-117_glass", false};
    {"Material.015", DIFFUSE , "Gear front_BaseColor", false};
    {"Material.016", DIFFUSE , "Gear Right_BaseColor", false};
    {"Material.017", DIFFUSE , "Gear Left_BaseColor", false};
    {"Material.018", DIFFUSE , "Aircraft 01_BaseColor", false};
    {"Material.019", DIFFUSE , "Aircraft 03_BaseColor", false};
    {"Material.020", DIFFUSE , "nighthawkgreen", false};
    {"Material.021", DIFFUSE , "nighthawkgreen", false};
    {"Material.022", DIFFUSE , "nighthawkgreen", false};
    {"Material.023", DIFFUSE , "nighthawkgreen", false};
    {"Material.024", DIFFUSE , "nighthawkgreen", false};
    {"Material.025", DIFFUSE , "nighthawkgreen", false};
    {"Material.026", DIFFUSE , "nighthawkgreen", false};
    {"Material.027", DIFFUSE , "nighthawkgreen", false};
    {"Material.028", DIFFUSE , "nighthawkgreen", false};
    {"Material.030", DIFFUSE , "nighthawkgreen", false};
    {"Material.031", DIFFUSE , "nighthawkgreen", false};
    {"Material.032", DIFFUSE , "nighthawkgreen", false};
    {"Material.034", DIFFUSE , "black", false};
    {"Material.036", DIFFUSE , "Aircraft 01_BaseColor", false};
    {"Material.037", DIFFUSE , "Aircraft 01_BaseColor", false};
    {"Material.039", DIFFUSE , "white", false};
    {"Material.040", DIFFUSE , "black", false};
    {"Material.042", DIFFUSE , "Bay Left_BaseColor", false};
    {"Material.043", DIFFUSE , "black", false};
    {"Material.044", DIFFUSE , "F-117_Turbine", false};
    {"Material.045", DIFFUSE , "Bay Left_BaseColor", false};
    {"Material.046", DIFFUSE , "F-117_frontmesh", false};
    {"Material.047", DIFFUSE , "Bay Right_BaseColor", false};
    {"Material.048", DIFFUSE , "Bay Front_BaseColor", false};
    {"Material.049", DIFFUSE , "F-117_glass", false};
    {"Material.050", DIFFUSE , "F-117_glass", false};
    {"Material.051", DIFFUSE , "black", false};
    {"Material.052", DIFFUSE , "grey", false};
    {"Material.053", DIFFUSE , "black", false};
    {"Material.054", DIFFUSE , "black", false};
    {"Material.055", DIFFUSE , "black", false};
    {"Material.056", DIFFUSE , "black", false};
    {"Material.057", DIFFUSE , "Gear Left_BaseColor", false};
    {"Material.058", DIFFUSE , "Gear Left_BaseColor", false};
    {"Material.059", DIFFUSE , "Gear Right_BaseColor", false};
    {"Material.060", DIFFUSE , "Gear Right_BaseColor", false};
    {"Material.061", DIFFUSE , "Bay Right_BaseColor", false};
    {"Material.062", DIFFUSE , "grey", false};
    {"Material.063", DIFFUSE , "Bay Left_BaseColor", false};
    {"Material.064", DIFFUSE , "Bay Right_BaseColor", false};
    {"Material.065", DIFFUSE , "Gear front_BaseColor", false};
    {"Material.066", DIFFUSE , "Missile Launcher_BaseColor", false};
    {"Material.067", DIFFUSE , "grey", false};
    {"material_1_853", DIFFUSE , "white", false};
    {"Missile", DIFFUSE , "Missile_BaseColor", false};
    {"Missile_Launcher", DIFFUSE , "Missile Launcher_BaseColor", false};
    {"Missile_Missile_Support_(2)", DIFFUSE , "Missile_BaseColor", false};
    {"Nose_bay", DIFFUSE , "Bay Front_BaseColor", false};
    {"PILOT_F22.002", DIFFUSE , "Pilot_F117", false};
    {"PILOT_F22.002", NORMAL_MAP , "Pilot_F117_nm", false};
    {"Right_bay_1", DIFFUSE , "Bay Right_BaseColor", false};
    {"Right_bay_2", DIFFUSE , "Bay Right_BaseColor", false};
    {"Right_bomb_door", DIFFUSE , "Door Missiles Right_BaseColor", false};
    {"seat", DIFFUSE , "seat_BaseColor", false};
}
